// Types centralisés dans @kza/shared — réexportés ici pour compatibilité
export type {
  SaleChannel,
  SaleStatus,
  ExpenseCategory,
  MovementType,
  Product,
  CreateProductDto,
  UpdateProductDto,
  StockMovement,
  CreateMovementDto,
  SaleItem,
  Sale,
  CreateSaleDto,
  Expense,
  CreateExpenseDto,
  UpdateExpenseDto,
  RecurringExpense,
  CreateRecurringExpenseDto,
  UpdateRecurringExpenseDto,
  SalesGoal,
  CreateGoalDto,
  UpdateGoalDto,
  BudgetForecast,
  BudgetForecastProduct,
  BudgetForecastExpense,
  ProductClassification,
  ProductAnalytics,
  GlobalKpis,
} from '@kza/shared';
