import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { CreateProductDto } from './dto/create-product.dto';

@Injectable()
export class ProductsService {
  constructor(private prisma: PrismaService) {}

  findAll(userId: string, businessId?: string) {
    const where = businessId ? { businessId } : { userId };
    return this.prisma.product.findMany({ where, orderBy: { createdAt: 'desc' } });
  }

  async create(dto: CreateProductDto, userId: string, businessId?: string) {
    let sku = dto.sku?.trim() || '';
    if (!sku) {
      let attempts = 0;
      do {
        sku = 'PRD-' + Math.random().toString(36).slice(2, 8).toUpperCase();
        const exists = await this.prisma.product.findFirst({ where: { userId, sku } });
        if (!exists) break;
      } while (++attempts < 10);
    }

    const product = await this.prisma.product.create({
      data: {
        name: dto.name,
        sku,
        category: dto.category ?? '',
        quantity: dto.quantity,
        alertThreshold: dto.alertThreshold,
        supplier: dto.supplier ?? '',
        acquisitionCost: dto.acquisitionCost,
        sellingPrice: dto.sellingPrice ?? 0,
        imageUrl: dto.imageUrl ?? null,
        entryDate: new Date(dto.entryDate),
        trackStock: dto.trackStock ?? true,
        userId,
        ...(businessId ? { businessId } : {}),
      },
    });

    if (dto.quantity > 0 && (dto.trackStock ?? true)) {
      await this.prisma.stockMovement.create({
        data: {
          productId: product.id,
          type: 'in',
          quantity: dto.quantity,
          reason: 'Stock initial',
          date: new Date(dto.entryDate),
          userId,
          ...(businessId ? { businessId } : {}),
        },
      });
    }

    return product;
  }

  async update(id: string, dto: Partial<CreateProductDto>, userId: string, businessId?: string) {
    const existing = await this.findOneOrFail(id, userId, businessId);

    const updated = await this.prisma.product.update({
      where: { id },
      data: {
        ...(dto.name !== undefined && { name: dto.name }),
        ...(dto.sku !== undefined && { sku: dto.sku }),
        ...(dto.category !== undefined && { category: dto.category }),
        ...(dto.quantity !== undefined && { quantity: dto.quantity }),
        ...(dto.alertThreshold !== undefined && { alertThreshold: dto.alertThreshold }),
        ...(dto.supplier !== undefined && { supplier: dto.supplier }),
        ...(dto.acquisitionCost !== undefined && { acquisitionCost: dto.acquisitionCost }),
        ...(dto.sellingPrice !== undefined && { sellingPrice: dto.sellingPrice }),
        ...(dto.imageUrl !== undefined && { imageUrl: dto.imageUrl }),
        ...(dto.entryDate !== undefined && { entryDate: new Date(dto.entryDate) }),
        ...(dto.trackStock !== undefined && { trackStock: dto.trackStock }),
      },
    });

    const tracksStock = dto.trackStock !== undefined ? dto.trackStock : (existing as any).trackStock ?? true;
    if (dto.quantity !== undefined && dto.quantity !== existing.quantity && tracksStock) {
      const delta = dto.quantity - existing.quantity;
      if (delta !== 0) {
        await this.prisma.stockMovement.create({
          data: {
            productId: id,
            type: delta > 0 ? 'in' : 'out',
            quantity: Math.abs(delta),
            reason: 'Ajustement manuel',
            date: new Date(),
            userId,
            ...(businessId ? { businessId } : {}),
          },
        });
      }
    }

    return updated;
  }

  async remove(id: string, userId: string, businessId?: string) {
    await this.findOneOrFail(id, userId, businessId);
    await this.prisma.product.delete({ where: { id } });
    return { id };
  }

  async reconcile(userId: string, businessId?: string) {
    const where = businessId ? { businessId } : { userId };
    const products = await this.prisma.product.findMany({ where });

    // Reasons auto-generated by the sales engine — excluded from manual movements
    // so we don't double-count with the SaleItem direct query below
    const SALE_REASONS = [
      'Vente', 'Vente confirmée',
      'Retour — vente annulée', 'Retour — vente suspendue', 'Retour — vente supprimée',
    ];

    let fixedCount = 0;

    const updated = await Promise.all(
      products
        .filter(p => p.trackStock)
        .map(async (product) => {
          // 1. Manual stock movements (stock initial, restocks, manual adjustments)
          //    Filter by productId only — businessId is null on old records
          const movements = await this.prisma.stockMovement.findMany({
            where: {
              productId: product.id,
              NOT: { reason: { in: SALE_REASONS } },
            },
            select: { type: true, quantity: true },
          });

          const fromMovements = movements.reduce((acc, m) =>
            m.type === 'in' ? acc + m.quantity : acc - m.quantity, 0);

          // 2. All currently-paid sale items — source of truth for deductions.
          //    Covers old sales that never created a StockMovement record.
          const paidItems = await this.prisma.saleItem.findMany({
            where: { productId: product.id, sale: { status: 'paid' } },
            select: { quantity: true },
          });

          const fromSales = paidItems.reduce((acc, i) => acc + i.quantity, 0);

          const quantity = Math.max(0, fromMovements - fromSales);

          if (Math.abs(quantity - product.quantity) < 0.001) return product;

          fixedCount++;
          return this.prisma.product.update({
            where: { id: product.id },
            data: { quantity },
          });
        }),
    );

    return { products: updated, fixedCount };
  }

  private async findOneOrFail(id: string, userId: string, businessId?: string) {
    const product = await this.prisma.product.findUnique({ where: { id } });
    if (!product) throw new NotFoundException('Produit introuvable');
    if (businessId && product.businessId && product.businessId !== businessId) {
      throw new NotFoundException('Produit introuvable');
    }
    if (!businessId && product.userId !== userId) throw new NotFoundException('Produit introuvable');
    return product;
  }
}
